### ISSUE TITLE
AllowedTag returns true on Exception in ActionBean

### ISSUE THREAD

**Issue by gabrielbratescu** [StripesFramework/stripes-stuff#10]
If an Exception is raised in ActionBean and it is not treated locally with try/catch then the Interceptor is not able to intercept LifecycleStage.ResolutionExecution,  and will not put the SecurityManager into the request. And by default, the AllowedTag is returnig true if the SecurityManager is not found in the request. 
Possible solutions: 
1. AllowedTag returns false if SecurityManager is not found.
2. Moving SecurityManager from request to session. This way you only put it once not in every request.

**Comment by christianpoitras** [comment]
I think the easiest fix is to set the SecurityManager in the request as soon as the interceptor is called.
I don't see any side effects of doing that.
